ruby welcome: "Welcome to the car loan calculator!"
first_name: "Please enter your first name:"
valid_name: "Please enter a valid name to proceed!"
loan_amount: "Enter the loan amount:"
invalid_input: "Invalid input! Enter a positive number greater than zero!"
invalid_entry: "Invalid entry! Enter number of years (mininum 1 year)"
interest_rate: "Enter the interest rate:"
interest_rate_example: "Example: 10 for 10% or 17.5 for 17.5%"
loan_years: "Enter the loan duration (in years):"
monthly_payment: "Your monthly payment is:"
another_calc: "Would you like to do another calculation? ('y' for yes / 'n' for no)"
invalid: "Invalid entry! Enter 'y' for another calculation or 'n' to quit."
thank_you: "Thank you for using car loan calculator, goodbye!"
